### ISSUE TITLE
successful installation - no data - no error message

### ISSUE THREAD

**Issue by Eismann82** [DevDavido/performance-audit-plugin#8] opened 2020-08-11 13:08 UTC
We have successfully installed the module in the current stable Matomo version. Even after several days we do not get any data and there are no error messages, neither in the Matomo logs nor in the server logs.

PHP version is 7.2.32-1+ubuntu18.04.1+deb.sury.org+1

Node.js & NPM are installed and my PHP configuration allows to execute commands via proc_open" and cromimum is also installed

hat could be the reason that we do not get any data?

**Comment by DevDavido** [comment] 2020-08-11 22:32
I'll work on a debug functionality which will help to figure out what's the cause.

**Comment by DevDavido** [comment] 2020-08-12 00:19
@Eismann82 
Please update to v1.0.6 and let me know the log output under `Administration` › `Performance` › `Plugin Check` so I can try to figure out what's causing the missing data.

**Comment by Eismann82** [comment] 2020-08-12 05:52
I do not get an error here either, but only the following information:

Log Output
[debug] Debug mode enabled
[info] A Performance Audit task is currently already running

**Comment by DevDavido** [comment] 2020-08-15 22:44
Thanks @Eismann82 for your quick feedback! I made several adjustments to the plugin, please let me know what's your log output now.

**Comment by Eismann82** [comment] 2020-08-16 15:55
Hi. Enclosed is the log. So far, I haven't been able to find any data in the reports. I installed version 1.0.7 yesterday and version 1.0.8 an hour ago.

[debug] Debug mode enabled
[info] Performance Audit task for site 1 will be started now
[debug] Performing audit for (site ID, URLs, URL count, emulated devices, runs): [1,["https://www.xxxxxx.xxx/"],1,["desktop","mobile"],[1]]
[info] Performing scheduled audit [1/1] of site 1 (device: desktop) for URL: https://www.xxxxxx.xxx/
[info] Performing scheduled audit [1/1] of site 1 (device: mobile) for URL: https://www.xxxxxx.xxx/
[debug] Audit file count: 2
[debug] Process Audit files: {"/var/www/share/analytics.xxxxxx.xyz/htdocs/plugins/PerformanceAudit/Audits/1-mobile-bc0bc2a0fa8e8794afce4b141ab97464fc6e4917-debug-1.json":{},"/var/www/share/analytics.xxxxxx.xyz/htdocs/plugins/PerformanceAudit/Audits/1-desktop-bc0bc2a0fa8e8794afce4b141ab97464fc6e4917-debug-1.json":{}}
[debug] Audit files processed as: {"1":{"bc0bc2a0fa8e8794afce4b141ab97464fc6e4917":{"mobile":{"firstContentfulPaint":{"0":2298},"largestContentfulPaint":{"0":6962},"interactive":{"0":5536},"speedIndex":{"0":2386},"totalBlockingTime":{"0":257},"cumulativeLayoutShift":{"0":0.6642071625754175},"score":{"0":64}},"desktop":{"firstContentfulPaint":{"0":2083},"largestContentfulPaint":{"0":6510},"interactive":{"0":5569},"speedIndex":{"0":2132},"totalBlockingTime":{"0":228},"cumulativeLayoutShift":{"0":0.3659391186548729},"score":{"0":38}}}}}
[debug] Final audit values: {"1":{"bc0bc2a0fa8e8794afce4b141ab97464fc6e4917":{"mobile":{"firstContentfulPaint":[2298,2298,2298],"largestContentfulPaint":[6962,6962,6962],"interactive":[5536,5536,5536],"speedIndex":[2386,2386,2386],"totalBlockingTime":[257,257,257],"cumulativeLayoutShift":[0,1,0],"score":[64,64,64]},"desktop":{"firstContentfulPaint":[2083,2083,2083],"largestContentfulPaint":[6510,6510,6510],"interactive":[5569,5569,5569],"speedIndex":[2132,2132,2132],"totalBlockingTime":[228,228,228],"cumulativeLayoutShift":[0,0,0],"score":[38,38,38]}}}}
[debug] Action IDs lookup table with URLs: [{"bc0bc2a0fa8e8794afce4b141ab97464fc6e4917":"7"},["bc0bc2a0fa8e8794afce4b141ab97464fc6e4917"]]
[info] Skipping database storing of results
[info] Performance Audit task for site 1 has finished

**Comment by DevDavido** [comment] 2020-08-16 16:34
Your log output looks good now, tomorrow the first results should show up in your performance report for the 16th Aug. Please let me know if that's the case.

**Comment by DevDavido** [comment] 2020-08-16 16:34
Your log output looks good now @Eismann82, tomorrow the first results should show up in your performance report for the 16th Aug. Please let me know if that's the case.

**Comment by Eismann82** [comment] 2020-08-17 06:10
It's not working. The plugin also generates other errors in other places in Matomo.

Matomo APP: The parameter ‘idSite’ isn’t set in the Request, and a default value wasn’t provided.


ScheduledReports (Core)

Key "name" for array with keys "category, module, action, dimension, metrics, metricsDocumentation, processedMetrics, constantRowsCount, imageGraphUrl, uniqueId" does not exist. in /var/www/share/analytics.xxxxxx.xyz/htdocs/plugins/ScheduledReports/templates/_addReport.twig 163 using PHP 7.4.8


I have excluded all other modules, the errors unfortunately come from your module.

**Comment by DevDavido** [comment] 2020-08-17 23:30
Is your cronjob running every hour? What's your cron output of the last 24 hours?

The other two errors I could reproduce and partially already fix, however the app seems to make internal requests different than the normal web version, so I need to take a deeper look in order to fully fix the app view.

**Comment by DevDavido** [comment] 2020-08-17 23:33
Is your Matomo cronjob running every hour? What's your [Matomo cron](https://matomo.org/docs/setup-auto-archiving/) output of the last 24 hours?

The other two errors I could reproduce and partially already fix, however the app seems to make internal requests different than the normal web version, so I need to take a deeper look in order to fully fix the app view.

**Comment by Eismann82** [comment] 2020-08-18 12:15
The cron job runs every 5 minutes. The cron output I first have to see how to get the data.

If the module is active I get errors in the Matomo logfiles. Enclosed the logfile.

[export_matomo_logs_20200818.txt](https://github.com/DevDavido/performance-audit-plugin/files/5090279/export_matomo_logs_20200818.txt)

**Comment by DevDavido** [comment] 2020-08-18 16:57
The two reported issues from yesterday are fixed with 1.0.10 now. Mobile app support should come in a future release.
To fix the original missing performance data bug, it's helpful to have the cron log. It would be great if you could get it, there's [an example in the docs](https://matomo.org/docs/setup-auto-archiving/#linux-unix-how-to-set-up-a-crontab-to-automatically-archive-the-reports) how to get it.

**Comment by Eismann82** [comment] 2020-08-19 06:37
With the version v1.0.10 the Matomo APP is working again.I don't get any data in the reports yet. I uploaded a cron errorlog here.  I try to collect more information.


[cron_archive_20200819.txt](https://github.com/DevDavido/performance-audit-plugin/files/5094421/cron_archive_20200819.txt)
[cron_archive_errors_20200819.txt](https://github.com/DevDavido/performance-audit-plugin/files/5094426/cron_archive_errors_20200819.txt)

**Comment by DevDavido** [comment] 2020-08-19 10:02
The `Too many arguments.` error from `cron_archive_errors_20200819.txt` is unrelated to my plugin I think. At least the stack trace shows nothing about the plugin. It would be great if you could send me the cron output of the last 24 hours.

**Comment by DevDavido** [comment] 2020-08-19 10:03
The `Too many arguments` error from `cron_archive_errors_20200819.txt` is unrelated to my plugin I think. At least the stack trace shows nothing about the plugin. It would be great if you could send me the cron output of the last 24 hours.

**Comment by DevDavido** [comment] 2020-08-19 10:03
The `Too many arguments` error from `cron_archive_errors_20200819.txt` is unrelated to my plugin I think. At least the stack trace shows nothing about the plugin. It would be great if you could send me the cron output of the last 24 hours after collecting the information.

**Comment by Eismann82** [comment] 2020-08-26 06:27
enclosed the error log of the last two days 

[cron_archive_errors_log.txt](https://github.com/DevDavido/performance-audit-plugin/files/5127964/cron_archive_errors_log.txt)

**Comment by DevDavido** [comment] 2020-08-26 16:54
Okay, there is no error in the log related to `PerformanceAudit`. How about the regular cron output of the last 24 hours? 

Also can you temporary install the [`Tasks Timetable`](https://plugins.matomo.org/TasksTimetable#preview) plugin and let me know if tasks like `Piwik\Plugins\PerformanceAudit\Tasks.auditSite_X` show up?

**Comment by Eismann82** [comment] 2020-08-26 17:07
the following scheduled tasks can be found in the module. i have rearranged the logs and can send them tomorrow because i currently only have the errorlogs.

Piwik\Plugins\PerformanceAudit\Tasks.auditSite_1 | Donnerstag, 27. August 2020 12:00:04(in 06:57:43)
Piwik\Plugins\PerformanceAudit\Tasks.auditSite_2 | Donnerstag, 27. August 2020 12:00:04(in 06:57:43)
Piwik\Plugins\PerformanceAudit\Tasks.auditSite_3 | Donnerstag, 27. August 2020 12:00:04(in 06:57:43)
Piwik\Plugins\PerformanceAudit\Tasks.auditSite_4 | Donnerstag, 27. August 2020 12:00:04(in 06:57:43)
Piwik\Plugins\PerformanceAudit\Tasks.auditSite_5 | Donnerstag, 27. August 2020 12:00:04(in 06:57:43)
Piwik\Plugins\PerformanceAudit\Tasks.auditSite_6 | Donnerstag, 27. August 2020 12:00:04(in 06:57:43)
Piwik\Plugins\PerformanceAudit\Tasks.auditSite_8 | Donnerstag, 27. August 2020 12:00:04(in 06:57:43)
Piwik\Plugins\PerformanceAudit\Tasks.auditSite_9 | Donnerstag, 27. August 2020 12:00:04(in 06:57:43)

**Comment by Eismann82** [comment] 2020-08-27 06:41
enclosed the logfile of the last night

[cron_archive_log.txt](https://github.com/DevDavido/performance-audit-plugin/files/5134522/cron_archive_log.txt)

**Comment by DevDavido** [comment] 2020-08-27 13:25
It shows the audit is scheduled correctly, however the audit itself doesn't start as there is an (old) audit task marked as running in the database.

- Can you post the output of `ps aux | grep -i node` on your server shell?
- Can you delete the row with `option_name` = `hasRunningPerformanceAuditTask` in your Matomo database table named `option`? Afterwards post the latest log file of the previous night again?

**Comment by Eismann82** [comment] 2020-08-27 13:33
hasRunningPerformanceAuditTask is deleted and here is the output of
$ ps aux | grep -i node
root      4060  0.0  1.3 1248480 84392 ?       Ssl  Aug24   1:24 /root/.nvm/versions/node/v10.4.0/bin/node /managed/application/managed.js
web-user 17120  0.0  0.0  14616   960 pts/2    S+   15:32   0:00 grep -i node

I will send the logfile tomorrow morning

**Comment by Eismann82** [comment] 2020-08-28 05:47
enclosed the logfile of the last night

[cron_archive_log_27-28_08_2020.txt](https://github.com/DevDavido/performance-audit-plugin/files/5140232/cron_archive_log_27-28_08_2020.txt)

**Comment by DevDavido** [comment] 2020-08-28 10:24
Do you see any performance reports for today?

**Comment by Eismann82** [comment] 2020-08-28 10:31
unfortunately no. the process of capturing seems to be running because i see it in the realtime monitoring of the server.

can the process of creating reports be initiated manually via the console?

**Comment by DevDavido** [comment] 2020-08-28 11:10
Okay, yes then it's still performing the audits for all urls. The reports will be automatically generated after all audits have been performed on a per site basis, so you can directly access the reports for finished site X after they're performed, even while audits are still performed for site Y. To generate partial reports (manually via console) while audits for that site are still performed isn't possible. However, I have already planned to implement an option to group certain URLs together, which should reduce the total audit time (significantly) if you have lots of URLs which only differ in their query string (like in your case). You can always change the site setting `Number of performance audit iterations` to 1 which will return results way faster but decreases the stability of the results on the other hand.

Let me know if you see the performance reports after the audits have finished 👍

**Comment by DevDavido** [comment] 2020-08-28 22:33
On a side note: Since 1.0.11 you can remove query strings from URLs now, in your case this should allow to speed up the total audit time if you enable this setting in your site settings.

**Comment by Eismann82** [comment] 2020-08-31 06:27
Good morning, unfortunately it's still not working, but there are now errors in the log files.
[cron_archive_31082020.txt](https://github.com/DevDavido/performance-audit-plugin/files/5148634/cron_archive_31082020.txt)

**Comment by DevDavido** [comment] 2020-08-31 12:05
Okay, the error `"General error: 2006 MySQL server has gone away"` is related to the database which opens up a whole new array of [possible causes](https://haydenjames.io/mysql-server-has-gone-away-error-solutions/). 

---------

Can you navigate to your `plugins/PerformanceAudit` folder on your server, create the patch file [alter_db_timeout_config.txt](https://github.com/DevDavido/performance-audit-plugin/files/5150103/alter_db_timeout_config.txt) and apply the patch like that (assuming your have git installed on your server):
`git apply alter_db_timeout_config.txt`
The patch temporarily extends the server timeout configuration of `wait_timeout`/`interactive_timeout`.

Also make sure that there is currently no node task of the plugin running and there's no row with `option_name` = `hasRunningPerformanceAuditTask` in your Matomo database table named `option` as [described before](https://github.com/DevDavido/performance-audit-plugin/issues/8#issuecomment-681947229).
Let me know via the latest log file if the error is gone after the next scheduled plugin run.

**Comment by Eismann82** [comment] 2020-08-31 12:40
Who can I stop the node task of the plugin?

error: patch failed: Tasks.php:87
error: Tasks.php: patch does not apply

**Comment by DevDavido** [comment] 2020-08-31 12:55
> Who can I stop the node task of the plugin?

List all node processes with `ps aux | grep -i node` and stop the PerformanceAudit ones with `kill -9 [PID]` whereas `[PID]` is the first number in each line of the output of `ps aux | grep -i node`.


> error: patch failed: Tasks.php:87
> error: Tasks.php: patch does not apply

Try to run in the PerformanceAudit folder `git apply --reject --whitespace=fix alter_db_timeout_config.txt` and let me know the content of all `*.rej` files in the same folder after executing the command.

**Comment by Eismann82** [comment] 2020-08-31 13:00
here the output

git apply --reject --whitespace=fix alter_db_timeout_config.txt
Checking patch Tasks.php...
error: while searching for:
            $this->logDebug('Debug mode enabled');
        }
        if ($this->hasAnyTaskRunning() && !$this->isInDebugMode()) {
            $this->logInfo('A Performance Audit task is currently already running');
            return;
error: patch failed: Tasks.php:87
error: while searching for:
        }
        Log::error($message);
    }
}
error: patch failed: Tasks.php:709
Applying patch Tasks.php with 2 rejects...
Rejected hunk #1.
Rejected hunk #2.

**Comment by Eismann82** [comment] 2020-08-31 13:02
here the output

git apply --reject --whitespace=fix alter_db_timeout_config.txt
Checking patch Tasks.php...
error: while searching for:
            $this->logDebug('Debug mode enabled');
        }
        if ($this->hasAnyTaskRunning() && !$this->isInDebugMode()) {
            $this->logInfo('A Performance Audit task is currently already running');
            return;
error: patch failed: Tasks.php:87
error: while searching for:
        }
        Log::error($message);
    }
}
error: patch failed: Tasks.php:709
Applying patch Tasks.php with 2 rejects...
Rejected hunk #1.
Rejected hunk #2.

**Comment by Eismann82** [comment] 2020-08-31 13:03
diff a/Tasks.php b/Tasks.php	(rejected hunks)
@@ -87,6 +87,9 @@ class Tasks extends BaseTasks
             $this->logDebug('Debug mode enabled');
         }
 
+        $this->setDatabaseConnectionConfiguration();
+        $this->logInfo('Database configuration: ' . json_encode(Db::get()->fetchAll('SHOW VARIABLES')));
+
         if ($this->hasAnyTaskRunning() && !$this->isInDebugMode()) {
             $this->logInfo('A Performance Audit task is currently already running');
             return;
@@ -709,4 +712,10 @@ class Tasks extends BaseTasks
         }
         Log::error($message);
     }
+
+    private function setDatabaseConnectionConfiguration()
+    {
+        Db::get()->exec('SET SESSION wait_timeout=604800;');
+        Db::get()->exec('SET SESSION interactive_timeout=604800;');
+    }
 }

**Comment by DevDavido** [comment] 2020-08-31 13:11
Are you on the latest plugin version 1.0.11? If the patch still doesn't work, just replace Tasks.php with [this file](https://gist.github.com/DevDavido/cf479619b589ba81d2e7cc38609dd77a), it's the Tasks.php file with the applied patch.

**Comment by Eismann82** [comment] 2020-08-31 13:21
we have installed the newest version (1.0.11) and also exchanged the file once again. There is still the following output

`diff a/Tasks.php b/Tasks.php	(rejected hunks)
@@ -87,6 +87,9 @@ class Tasks extends BaseTasks
             $this->logDebug('Debug mode enabled');
         }
 
+        $this->setDatabaseConnectionConfiguration();
+        $this->logInfo('Database configuration: ' . json_encode(Db::get()->fetchAll('SHOW VARIABLES')));
+
         if ($this->hasAnyTaskRunning() && !$this->isInDebugMode()) {
             $this->logInfo('A Performance Audit task is currently already running');
             return;
@@ -709,4 +712,10 @@ class Tasks extends BaseTasks
         }
         Log::error($message);
     }
+
+    private function setDatabaseConnectionConfiguration()
+    {
+        Db::get()->exec('SET SESSION wait_timeout=604800;');
+        Db::get()->exec('SET SESSION interactive_timeout=604800;');
+    }
 }
`

**Comment by DevDavido** [comment] 2020-08-31 18:16
> we have installed the newest version (1.0.11) and also exchanged the file once again. There is still the following output

After you exchanged the Tasks.php file there's no need to apply the patch. Since you exchanged it, just make this sure:

> Also make sure that there is currently no node task of the plugin running and there's no row with `option_name` = `hasRunningPerformanceAuditTask` in your Matomo database table named `option` as [described before](https://github.com/DevDavido/performance-audit-plugin/issues/8#issuecomment-681947229).
> Let me know via the latest log file if the error is gone after the next scheduled plugin run.

**Comment by Eismann82** [comment] 2020-09-04 07:20
unfortunately it still does not work, here are the latest error logs

[cron_archive_202009040.txt](https://github.com/DevDavido/performance-audit-plugin/files/5173263/cron_archive_202009040.txt)

**Comment by DevDavido** [comment] 2020-09-04 23:39
It seems we might be close to have it all fixed, the performance audits itself run somewhat smooth now. The only real error left from the log right now is some issue with a url lookup table. Information which help me to debug that are already part of the plugin, however it needs a log level of DEBUG to output these information. The quickest and easiest to get the output of these debug information would be to replace the plugin `Tasks.php` file with [this](https://gist.github.com/DevDavido/cf479619b589ba81d2e7cc38609dd77a), afterwards I need the log output which contains lines like `Action IDs lookup table with URLs:` [...]

Thank you for helping me and other users, making this plugin more robust and bug free! 👍

**Comment by Eismann82** [comment] 2020-09-06 07:49
now it seems to work and I get data in the reports

**Comment by DevDavido** [comment] 2020-09-06 20:08
Great! So no more errors in the logs?

**Comment by Eismann82** [comment] 2020-09-07 05:49
Enclosed I would like to send you the logfile. I'm monitoring it now for a few days to see if there are any more bugs.

[cron_archive_20200907.txt](https://github.com/DevDavido/performance-audit-plugin/files/5181239/cron_archive_20200907.txt)

**Comment by DevDavido** [comment] 2020-09-07 10:48
Ok, have you replaced the `Tasks.php` file?

> The quickest and easiest to get the output of these debug information would be to replace the plugin `Tasks.php` file with [this](https://gist.github.com/DevDavido/cf479619b589ba81d2e7cc38609dd77a), afterwards I need the log output which contains lines like `Action IDs lookup table with URLs:` [...]

**Comment by Eismann82** [comment] 2020-09-07 12:13
Yes, I replaced the file. just did it again. but without changing the logfiles.

**Comment by Eismann82** [comment] 2020-09-10 06:38
Unfortunately, something still seems not to work. The data of the reports can only be seen on 06.09.2020. The process seems to be running, but the reports are not created. Enclosed the logfile.
[cron_archive_20200910.txt](https://github.com/DevDavido/performance-audit-plugin/files/5199584/cron_archive_20200910.txt)

**Comment by DevDavido** [comment] 2020-09-10 12:26
Around 2% (5 of 235) of your URLs had no matching entry in the related database table which resulted in those SQL error messages in your log file. I can have a deeper look why's that the case. Can you send me a dump of your `log_action` table? If you want you can send it to [this email](https://github.com/DevDavido/performance-audit-plugin/blob/main/composer.json#L8).

Meanwhile, to work around this error, replace your `Tasks.php` with [this updated file](https://gist.github.com/DevDavido/cf479619b589ba81d2e7cc38609dd77a). Afterwards, please let me know if you still encounter those errors in your log file?

**Comment by Eismann82** [comment] 2020-09-10 13:26
I replaced the file and sent the SQL dump via wetransfer.

**Comment by DevDavido** [comment] 2020-09-10 14:39
I received the dump, thanks. While debugging I realised that the log file have anonymised URLs, can you also send me via email the log file without any changes too?

**Comment by DevDavido** [comment] 2020-09-10 14:41
I received the SQL dump, thanks. While debugging I realised that the log file has anonymised URLs, can you send me via email the log file without any changes too?

**Comment by Eismann82** [comment] 2020-09-10 14:45
have just sent the logfile via wettransfer

**Comment by DevDavido** [comment] 2020-09-10 23:16
Thanks @Eismann82 👍 
It seems like in the previous release an edge case was introduced with the _URL query string removal option_ which eventually caused the SQL error. Please update to v1.1.0 and afterwards replace the [`Tasks.php`](https://gist.github.com/DevDavido/cf479619b589ba81d2e7cc38609dd77a) file. Let me know after the next audit if you still have (SQL) errors in your log file. You can send them via email again.

**Comment by Eismann82** [comment] 2020-09-11 05:29
The update is done and the file is replaced. I will contact you with the logfiles the next days.

**Comment by Eismann82** [comment] 2020-09-14 05:16
unfortunately there are fatal errors the logfiles I have sent by wettransfer

**Comment by DevDavido** [comment] 2020-09-14 14:09
> unfortunately there are fatal errors the logfiles [...]

I checked the logs and that fatal error was caused by `Piwik\Plugins\DBStats\Tasks.cacheDataByArchiveNameReports` which was unable to execute a command on the shell, however the underlying cause of it is the same as for the errors the PerformanceAudit plugin itself is experiencing. The operating system is not permitting to create new (audit) processes. For some inexplicable reason the audit was started simultaneously multiple times, which might be the reason why too many processes were active and the creation of new ones failed. I assume there were absolutely no changes/updates etc. made on your server during the weekend? It might be just a one-time race condition or an actual underlying problem. I created a quick workaround to hopefully reduce the risk for any new race conditions, please replace your [`Tasks.php`](https://gist.github.com/DevDavido/cf479619b589ba81d2e7cc38609dd77a), monitor it for another day and send me the logs as usual.

**Comment by Eismann82** [comment] 2020-09-14 14:22
There were no changes to our systems. I have replaced the file and will monitor it.

**Comment by DevDavido** [comment] 2020-09-20 20:44
Any news regarding the monitoring @Eismann82?

**Comment by Eismann82** [comment] 2020-09-21 05:34
At the beginning of last week it looked good. But after a planned failover test of our systems on Wednesday the process did not start again. Which is also a good thing, if you can set that some domains can be excluded (on and off per domain)

**Comment by DevDavido** [comment] 2020-09-21 23:39
I created a new issue for the enable/disable functionality: #24 

It seems like the plugin site audit must've been unexpectedly terminated during the failover test? Before each audit there's a flag (`hasRunningPerformanceAuditTask`) being set which will prevent any new audit from getting run until the current finished or timed out, even any internal failure is caught so it won't run into issues, however external factors (outside of the plugins scope) can't be caught directly. I could implement an automatic functionality to fix this stale state on a daily basis but it would create an issue with very long running site audits. I decided to implement a weekly reset (each Monday at midnight) and if anyone wants to fix/reset the state directly so audits gets scheduled the next possible time again, simply run the newly added (in v1.1.1) Matomo console command `console performanceaudit:clear-task-running-flag` which resets the flag.

Please let me know if everything is running smoothly after the plugin update / console command execution...

**Comment by Eismann82** [comment] 2020-09-22 06:32
I will monitor it and get back to you

**Comment by Eismann82** [comment] 2020-10-06 05:53
Hi @DevDavido , sorry for the delayed response. I was away on business. Meanwhile it looks good and the reports are displayed and there are no more errors.

**Comment by DevDavido** [comment] 2020-10-06 13:58
Perfect! 💯

**Closed by DevDavido** 2020-10-06 13:58 UTC
Labels: bug, need more information
